/* soapZMM036F1Proxy.h
   Generated by gSOAP 2.8.129 for erp.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapZMM036F1Proxy_H
#define soapZMM036F1Proxy_H
#include "soapH.h"

    class SOAP_CMAC ZMM036F1Proxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'ZMM036F1Proxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in erp.h, if any
        /// Construct a proxy with new managing context
        ZMM036F1Proxy();
        /// Copy constructor
        ZMM036F1Proxy(const ZMM036F1Proxy& rhs);
        /// Construct proxy given a shared managing context
        ZMM036F1Proxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        ZMM036F1Proxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        ZMM036F1Proxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        ZMM036F1Proxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ZMM036F1Proxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ZMM036F1Proxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~ZMM036F1Proxy();
        /// Initializer used by constructors
        virtual void ZMM036F1Proxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ZMM036F1Proxy *copy();
        /// Copy assignment
        ZMM036F1Proxy& operator=(const ZMM036F1Proxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'ZMM036F1' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ZMM036F1(_ns1__ZMM036F1 *ns1__ZMM036F1, _ns1__ZMM036F1Response &ns1__ZMM036F1Response) { return this->ZMM036F1(NULL, NULL, ns1__ZMM036F1, ns1__ZMM036F1Response); }
        /// Web service synchronous operation 'ZMM036F1' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ZMM036F1(const char *soap_endpoint_url, const char *soap_action, _ns1__ZMM036F1 *ns1__ZMM036F1, _ns1__ZMM036F1Response &ns1__ZMM036F1Response) { return this->send_ZMM036F1(soap_endpoint_url, soap_action, ns1__ZMM036F1) || this->recv_ZMM036F1(ns1__ZMM036F1Response) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ZMM036F1' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ZMM036F1(const char *soap_endpoint_url, const char *soap_action, _ns1__ZMM036F1 *ns1__ZMM036F1);
        /// Web service asynchronous operation 'recv_ZMM036F1' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ZMM036F1(_ns1__ZMM036F1Response &ns1__ZMM036F1Response);
        //
        /// Web service synchronous operation 'ZMM036F1' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ZMM036F1_(_ns1__ZMM036F1 *ns1__ZMM036F1, _ns1__ZMM036F1Response &ns1__ZMM036F1Response) { return this->ZMM036F1_(NULL, NULL, ns1__ZMM036F1, ns1__ZMM036F1Response); }
        /// Web service synchronous operation 'ZMM036F1' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ZMM036F1_(const char *soap_endpoint_url, const char *soap_action, _ns1__ZMM036F1 *ns1__ZMM036F1, _ns1__ZMM036F1Response &ns1__ZMM036F1Response) { return this->send_ZMM036F1_(soap_endpoint_url, soap_action, ns1__ZMM036F1) || this->recv_ZMM036F1_(ns1__ZMM036F1Response) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ZMM036F1' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ZMM036F1_(const char *soap_endpoint_url, const char *soap_action, _ns1__ZMM036F1 *ns1__ZMM036F1);
        /// Web service asynchronous operation 'recv_ZMM036F1' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ZMM036F1_(_ns1__ZMM036F1Response &ns1__ZMM036F1Response);
    };
#endif
